### ISSUE TITLE
Allow strings + parse for Date Validators

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/fonk#66]
**Issue:**

Right now date validators only accept Date as valid type and thirs party controls may return an string.

We don't want to mess up with moment, luxor.. this should be up to the consumer of the library.

**Proposal:**

In validators args:

```javascript
{
  parseStringToDateFn : (date : string) => Date;
}
```

By doing this we pass the responsability of formatting the date to the application consuming the library (it can use his lib of choice, plus format of choice).

We could add this as a generic setting for each date validator (Set it up in one place).

All ES6/TS solution no providers and suchs tuff we want to keep being framework agnostic

This applies to 

- PreviousDate validation.
- LaterDate validation.
- RangeDate validation.

**Comment by Nasdan** [comment]
Check:

- [previous-date](https://github.com/Lemoncode/fonk-previous-date-validator)
- [later-date](https://github.com/Lemoncode/fonk-later-date-validator)
- [range-date](https://github.com/Lemoncode/fonk-range-date-validator)
