### ISSUE TITLE
Abstract validators arguments passing

### ISSUE THREAD

**Issue by jgoux** [Lemoncode/fonk#91]
Hello,

Great work on this library, I like the more functional approach it takes with validators as an array!

I was wondering why do we have to pass the validator key as in `[Validators.required.validator]` instead of `[Validators.required]` ?

I think that it adds noise, and the validation function consuming the array could call it itself?

Something like this would be very nice :
```js
import { createFormValidation, Validators as V } from '@lemoncode/fonk';

const validationSchema = {
  field: {
    user: [V.required, { validator: V.minLength, customArgs: { length: 10 }}]
  },
};

export const formValidation = createFormValidation(validationSchema);
```

**Comment by brauliodiez** [comment]
Hi Julien,

Thanks a lot for your feedback, agree it can be a bit verbose for the built in validators, will check it with the team and come back to you.

**Comment by brauliodiez** [comment]
Hi Julien, 

Just checked with @Nasdan, the idea of grouping this, is to group a given validator related function, in this case a given validator has as well an associated _setErrorMessage_ function (this function allows you to customize the validator error message(s), likely this could be used in any application that has to provide support for multiple languages). 

Current definition is:

```typescript
interface FieldValidator {
  validator: FieldValidationFunctionSyncAsync;
  setErrorMessage: (message: string | string[]) => void;
}
```

We were not sure what could be the best approach, on one hand you are right it adds more verbosity, on the other we thought that grouping validators related functions could be helpful.

**Comment by jgoux** [comment]
Hello Braulio,

I understand the idea behind wrapping the validator but maybe you could accept the `FieldValidator` type as well in the validators array, and when one is passed, call its validator's key? Best of both worlds? 😄

**Comment by brauliodiez** [comment]
That's  a great idea ! 

Just thinking loud on the typings side it could be something like:

```diff
export interface FieldValidationSchema {
-  [fieldId: string]: FieldValidation[];
+  [fieldId: string]: (FieldValidation | FieldValidator)[];
}
````

Then on the implementation side we only need to add a guard to check what we get back, then just access _validator.validation_ in case we get a FieldValidator.

And what I like the most from the approach you are mentioning is that we don't introduce any breaking change.

@Nasdan What's your take on this?

Thanks @jgoux

**Comment by jgoux** [comment]
You should also modify the type of [FullFieldValidation](https://github.com/Lemoncode/fonk/blob/master/src/model/field-validator.model.ts#L23)'s validator key I think.

**Comment by Nasdan** [comment]
Hello @jgoux 

We have published a beta including this enhancement:

https://www.npmjs.com/package/@lemoncode/fonk/v/1.2.1

A codesandbox:

https://codesandbox.io/s/validate-field-ts-example-yl2so

We will make a release in the following days

**Comment by jgoux** [comment]
Thanks a lot for the feature! 🌟
