### ISSUE TITLE
Validating nested array fields

### ISSUE THREAD

**Issue by sijad** [Lemoncode/fonk#92]
currently it's not possible to validate nested array fields, for example:

```js
const myRecord = {
  translations: [
    {title: 'my record title', hint: 'my record hint'},
    {title: 'my record other title', hint: 'my record other hint'}
  ],
}
```

it's not possible to apply validating to all of `translations` indexes.

something like this should work:

```js
const validationSchema = {
  field: {
    'translations': [
      {
        validator: Validators.maxLength.validator,
        customArgs: { length: 5 }, // Valid translations for length lower than 5 item
      }
    ],
    'translations.*.title': [Validators.required.validator],
    'translations.*.hint': [Validators.required.validator],
  },
};
```

for more info please also see Lemoncode/fonk-formik#9

**Comment by brauliodiez** [comment]
That's an excellent suggestion.

Going for the 'arrayfieldname.*.field' wold work for validations like:
  - A given validation that is not related with other fields.
  - A given validation that is related with record fields.

We have to think about covering the following case:

- A given validation that is dependant on another field array (e.g. email and confirm email fields), I see here two approaches:
   - First iteration: do not cover this case for arrays (you must implement a custom validator for cases like this).
  - Second iteration: we could pass something like 'translations.*.conifrmemail', this would impact all validators implemented, IMHO it would be quite powerful, but it would add some additional complexity to implementing a validator.

What do you think?

**Comment by sijad** [comment]
I like costume validation method more, I think it's more powerful than `.*.`, for example:

```js
const validationSchema = {
  field: {
    'translations': [
      {
        validator: Validators.array.validator,
        customArgs: {
          field: {
            title: [Validators.required.validator],
            hint: [Validators.required.validator],
          },
        },
      }
    ],
  },
};
```

it's not hacky as `.*.` and much cleaner.

**Comment by brauliodiez** [comment]
The second approach you are mentioning has a great benefit:

- We place all the complexity and specialization in a separate component (Validators.array.validator), where no other modules depend.
- We just add some low impact update on the fonk engine it self (updates on satellite modules like fonk-formik or fonk-final-form is low).
- We don't need to update all the validators, they keep on working out of the box.

I think we could make a clean implementation if we add one restriction to the array validations:

- For a given row it's _values_ field (viewmodel / record) is just the row itself. If we need to gain has access to the outer viewmodel (the full record), we need to implement a custom validator.

If we stick to this restriction I think the implementation will be clean, basic validators will work out of the box, dependent field validations will work out of the box (taking into account that they cannot refer to fields that are outside the row being edited), for scenario where a field in a row would need to access the main viewmodel, the developer can build custom validator implementation (edge case, sounds fair, a little bit of custom code needed).

If we want to allow developers to create such custom validators that can access both the current row viewmodel and the full viewmodel, the ArrayValidator could pass as an extra parameter to each validator the outer viewmodel (the full record).

What do you think?

**Comment by sijad** [comment]
agreed, I think `Validators.array.validator` is more readable too.

**Comment by jgoux** [comment]
I was going to make an issue about it. Arrays are quite common when dealing with a lot of many to many relationships.

The ArrayValidator seems like a great idea!

**Comment by brauliodiez** [comment]
Hello @jgoux, totally agree, we are working on it, it will take us sometime because likely it will impact our Fonk core, hope to start sharing further ideas and progress soon

**Comment by brauliodiez** [comment]
We are working on defining the best approach, @LissetteIbnz has been further working on the idea that @sijad  provided, right now we are checking the following approaches:

**a. Including an advanced array validator**

```typescript
const validationSchema = {
  field: {
    'translations': [
      {
        validator: Validators.array.validator,
        customArgs: {
          field: {
            title: [Validators.required.validator],
            hint: [Validators.required.validator],
          },
        },
      }
    ],
  },
};
```
We have found the following challenges:
  - On nested fields it could be an issue, what field is the array? we could use some wildcard approach to mark it.
  - How do we know what is the current row being edited?

**b. Adding a new section to the Validation Schema**

```typescript
const validationSchema: ValidationSchema = {
  array: {
    contacts: {
      field: {
        name: [Validators.required],
        email: [Validators.required, Validators.email],
      },
    },
  },
  field: {
    user: [Validators.required],
    password: [Validators.required],
  },
};
```

This one seem to be more flexible, what we have found so far:
  - Using _validateForm_ it will be straightforward.
  - Using _validateField_, we will need to decide:
      - Adding some extra param to this method to indicate the key (maybe array index, or field / key like in e.g. react map).
     - Creating a new method called _validateArrayField_.

Personally I prefer to introduce _validateArrayField_ we can just define specific parameters for this case and avoid overcomplicate the validateField method.

On the other hand we have to check how can we integrate all this in form state management solutions like React Final Form or Formik.

**Comment by brauliodiez** [comment]
We have news about this issue,

We have just released a Beta version including an ArrayValidator:
https://github.com/Lemoncode/fonk/releases/tag/v1.4.0-beta.1

Example codesandbox:
https://codesandbox.io/s/array-validator-formik-0c1dl?file=/form-validation.js

We are generating now more ellaborated examples.

Finally we have just created and ArrayValidator that is included in the main fonk library.

**Comment by brauliodiez** [comment]
**Published Release version:**

https://github.com/Lemoncode/fonk/releases/tag/v1.4.0

_**Examples**_

**React Final Form**

Shopping Cart(JavaScript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/react-final-form/js/shopping-cart-array-validator

Shopping Cart(Typescript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/react-final-form/ts/shopping-cart-array-validator

Multiple users creation(JavaScript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/react-final-form/js/multiple-user-creation-array-validator

Multiple users creation(Typescript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/react-final-form/ts/multiple-user-creation-array-validator


**Formik**

Shopping Cart (JavaScript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/formik/js/shopping-cart-array-validator

Multiple users creation (JavaScript)
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/formik/js/multiple-user-creation-array-validator

**Vanillajs**

Shopping Cart
https://codesandbox.io/s/github/lemoncode/fonk/tree/master/examples/vanilla/js/shopping-cart-array-validator

**Documentation:**

https://lemoncode.github.io/fonk-doc/validators/builtin-validators
